name: "PAUL - Patch Automation Using LLMs"
description: "Automatically analyzes an issue and creates a PR suggestion"
author: "Michael-Raphael Kostagiannis"

inputs:
  owner:
    description: 'GitHub repository owner username'
    required: true

  repo:
    description: 'Repository name'
    required: true

  issue:
    description: 'Issue number (int)'
    required: true

  openai-api-key:
    description: "OpenAI API Key"
    required: true

  github-token:
    description: "GitHub Token for creating PRs"
    required: true

  model:
    description: "OpenAI model to use (default: gpt-4o-mini)"
    required: false
    default: "gpt-4o-mini"

runs:
  using: "docker"
  image: "docker://ghcr.io/mikeraphk/paul:latest"
  args:
    - --owner
    - ${{ inputs.owner }}
    - --repo
    - ${{ inputs.repo }}
    - --issue
    - ${{ inputs.issue }}
    - --model
    - ${{ inputs.model }}
  env:
    OPENAI_API_KEY: ${{ inputs.openai-api-key }}
    GITHUB_TOKEN: ${{ inputs.github-token }}
