from langchain_community.callbacks.openai_info import OpenAICallbackHandler
from langchain_community.tools import ReadFileTool, WriteFileTool, ListDirectoryTool
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI
from langgraph.errors import GraphRecursionError

import json
import re
import uuid

from . import github_utils as ghu
from .graph_builder import build_graph
from github import Github


def run_paul(owner: str, repo_name: str, issue_number: int, GITHUB_TOKEN: str, OPENAI_API_KEY: str) -> None:
    print("Starting PAUL...")
    print(f"Owner: {owner}")
    print(f"Repo: {repo_name}")
    print(f"Issue Number: {issue_number}")
    gh = Github(GITHUB_TOKEN)

    # Get issue
    repo = gh.get_repo(f"{owner}/{repo_name}")
    issue = repo.get_issue(number=issue_number)

    # Print out info
    print(f"Issue Title: {issue.title}")
    print(f"Issue Body: {issue.body}")
    print(f"Labels: {[label.name for label in issue.labels]}")
    print(f"State: {issue.state}")
    print(f"Author: {issue.user.login}")

    print("Exiting PAUL...")
    exit()


    # Create new branch
    branch_name = f"PAUL-branch-{uuid.uuid4().hex[:8]}"
    print(f"\nBranching to '{branch_name}'...\n")
    repo.git.checkout("-b", branch_name)

    # Create the graph
    print("Initializing ReAct graph...\n")
    callback = OpenAICallbackHandler()
    model = ChatOpenAI(model="gpt-4o-mini", openai_api_key=OPENAI_API_KEY, callbacks=[callback], request_timeout=15.0)
    tools = [ReadFileTool(), WriteFileTool(), ListDirectoryTool()]
    APP = build_graph(tools=tools, llm=model)

    # Initialize system message and query
    print("Initializing chat history...\n")
    chat_history = []
    system_message = SystemMessage(content="""
        You are an AI software engineer. Your task is to automatically fix issues in a local GitHub repository located at ./cloned_repo. For each task:
            1. Read and understand the GitHub issue provided to you.
            2. Locate the relevant part(s) of the codebase inside ./cloned_repo that need to be changed.
            3. Modify the code to resolve the issue while maintaining functionality, clarity, and style.
            4. Generate a concise and informative git commit message describing the fix.
            5. Prepare a pull request summary explaining what was fixed, how it was fixed, and any tests added or run.
        Constraints:
            1. Only make changes necessary to fix the issue.
            2. Prefer minimal, safe, and testable changes.
            3. Do not introduce unrelated modifications.
            4. Assume the repository uses standard Git practices.
            5. Only use tools when strictly necessary, otherwise end the conversation.
        Respond with a JSON object containing the following fields:
            - "modified_files": The list of modified files.
            - "commit_msg": The commit message.
            - "pr_title": The pull request title.
            - "pr_body": The pull request body. Do not include the issue number in the body.
    """)
    chat_history.append(system_message)
    query = HumanMessage(content=f"""
        Issue Title: {issue['title']}
        Issue Body: {issue['body']}
        Issue Number: {issue['number']}
    """)
    chat_history.append(query)

    # Invoke the LLM
    print("Invoking LLM...\n")
    try:
        output_state = APP.invoke({"messages" : chat_history})
    except GraphRecursionError as e:
        raise RuntimeError("Failed to provide a solution due to recursion limit. Exiting...") from e
    content = output_state["messages"][-1].content

    print("Creating pull request...\n")

    # Remove leading and trailing fences
    content = content.strip()
    if content.startswith("```"):
        content = re.sub(r"^```(?:json)?\s*", "", content)
        content = re.sub(r"\s*```$", "", content)
    content_json = json.loads(content)

    # Add more info to pr_body
    content_json["pr_body"] =  "> **Note:** This message was automatically generated by PAUL. Please review the proposed changes carefully before merging.\n\n" + content_json["pr_body"]
    content_json["pr_body"] += f"\n\nRelated to #{issue['number']}\n"
    content_json["pr_body"] += f"Tokens Used: {callback.total_tokens}\n"
    content_json["pr_body"] += f"Successful Requests: {callback.successful_requests}\n"
    content_json["pr_body"] += f"Total Cost (USD): {callback.total_cost:.6f}\n"
    ghu.create_pr(repo, content_json["commit_msg"], owner, repo_name, GITHUB_TOKEN, content_json["pr_title"], content_json["pr_body"], default_branch)
    print("\nPull request created successfully!")    