from github.Repository import Repository
from github.PullRequest import PullRequest
from langchain_community.callbacks.openai_info import OpenAICallbackHandler
from subprocess import run
from typing import Tuple, Dict

import json
import os
import re



def check_env_vars() -> Tuple[str, str]:
    """
    Loads and validates required environment variables.

    Returns:
        Tuple[str, str]: A tuple containing the GitHub token and OpenAI API key.

    Raises:
        ValueError: If either `GITHUB_TOKEN` or `OPENAI_API_KEY` is not set.
    """

    GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
    if not GITHUB_TOKEN:
        raise ValueError("GITHUB_TOKEN is not set.")

    OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
    if not OPENAI_API_KEY:
        raise ValueError("OPENAI_API_KEY is not set.")
    
    return GITHUB_TOKEN, OPENAI_API_KEY



def setup_git_environment() -> None:
    """
    Set up the local Git environment for safe repository operations in a Docker-based GitHub Action.

    Raises:
        subprocess.CalledProcessError: If any git command fails.
        AssertionError: If the .git directory does not exist in /github/workspace.
    """
    os.chdir("/github/workspace")
    os.environ["GIT_DIR"] = os.path.abspath(".git")
    os.environ["GIT_WORK_TREE"] = os.getcwd()
    run(["git", "config", "user.email", "paul-bot@users.noreply.github.com"], check=True)
    run(["git", "config", "user.name", "paul-bot"], check=True)
    run(["git", "config", "--global", "--add", "safe.directory", os.getcwd()])



def parse_paul_response(content: str, issue_number: int, callback: OpenAICallbackHandler) -> Dict[str, str]:
    """
    Parse JSON response from PAUL.

    Args:
        content (str): The raw string content from the LLM, possibly wrapped in code fences.
        issue_number (int): The GitHub issue number for reference in the PR body.
        callback (OpenAICallbackHandler): The callback object containing LLM usage statistics.

    Returns:
        Dict[str, str]: The enriched JSON object containing PR details and additional metadata.
    """
    # Remove leading and trailing fences
    content = content.strip()
    if content.startswith("```"):
        content = re.sub(r"^```(?:json)?\s*", "", content)
        content = re.sub(r"\s*```$", "", content)
    content_json = json.loads(content)

    # Add more info to pr_body
    content_json["pr_body"] =  "> **Note:** This message was automatically generated by PAUL. Please review the proposed changes carefully before merging.\n\n" + content_json["pr_body"]
    content_json["pr_body"] += f"\n\nRelated to #{issue_number}\n"
    content_json["pr_body"] += f"Tokens Used: {callback.total_tokens}\n"
    content_json["pr_body"] += f"Successful Requests: {callback.successful_requests}\n"
    content_json["pr_body"] += f"Total Cost (USD): {callback.total_cost:.6f}\n"

    return content_json



def create_pull_request(content_json: Dict[str, str], branch_name: str, repo: Repository) -> PullRequest:
    """
    Commit local changes and create a pull request on GitHub.

    Args:
        content_json (Dict[str, str]): Dictionary containing the commit message, PR title, and PR body.
        branch_name (str): Name of the branch to push and use as the PR head.
        repo (Repository): PyGithub Repository object for the target repo.

    Returns:
        PullRequest: The created GitHub PullRequest object.
    """

    # Commit and push
    run(["git", "add", "."], check=True)
    run(["git", "commit", "-m", content_json["commit_msg"]], check=True)
    run(["git", "push", "--set-upstream", "origin", branch_name], check=True)

    # Create pull request
    pr = repo.create_pull(
        title=content_json["pr_title"],
        body=content_json["pr_body"],
        head=branch_name,
        base=repo.default_branch,
        draft=False
    )
    return pr